name: Docker

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        uses: mkeiji/kcicd/.github/workflows/ci-docker.yml@master
        with:
            build_context: ./
            dockerfile: ./Dockerfile
            image_suffix: ${{ github.repository }}
            release_branch: master
            build_args: ${{ vars.BUILD_ARGS }}
        secrets: inherit
