name: Docker

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set Envs
              run: |
                  SHOULD_RELEASE=$( [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/master" ] && echo true || echo false )
                  echo "SHOULD_RELEASE=${SHOULD_RELEASE}" >> $GITHUB_ENV
                  echo "VERSION=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Builder
              uses: docker/setup-buildx-action@v3

            - name: Log into GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./
                  file: ./Dockerfile
                  push: ${{ env.SHOULD_RELEASE }}
                  build-args: |
                      WS_URL=${{ env.WS_URL }}
                  tags: |
                      ghcr.io/${{ github.repository }}:latest
                      ghcr.io/${{ github.repository }}:${{ env.VERSION }}
