name: Docker

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        uses: mkeiji/kcicd/.github/workflows/ci-docker.yml@master
        with:
            build_context: ./
            dockerfile: ./Dockerfile
            release_branch: master
            build_args: "HOST_ADDR=${{ vars.HOST_ADDR }}"
        secrets: inherit
